import {
  User,
  Student,
  Course,
  Product,
  Instructor,
  Enrollment,
  Certificate,
  Payment,
} from '@/types/index';

// Instructors
export const INSTRUCTORS: Instructor[] = [
  {
    id: 'instr-001',
    name: 'Dr. Sarah Johnson',
    email: 'sarah@ifybugsy.com',
    bio: 'Expert in web development with 10+ years experience',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    specialization: 'Web Development',
    yearsExperience: 10,
  },
  {
    id: 'instr-002',
    name: 'Prof. Michael Chen',
    email: 'michael@ifybugsy.com',
    bio: 'Data Science specialist with published research',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    specialization: 'Data Science',
    yearsExperience: 8,
  },
  {
    id: 'instr-003',
    name: 'Emily Rodriguez',
    email: 'emily@ifybugsy.com',
    bio: 'Mobile app development expert',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    specialization: 'Mobile Development',
    yearsExperience: 7,
  },
  {
    id: 'instr-004',
    name: 'James Wilson',
    email: 'james@ifybugsy.com',
    bio: 'Cloud architecture and DevOps specialist',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    specialization: 'Cloud & DevOps',
    yearsExperience: 9,
  },
];

// Courses
export const COURSES: Course[] = [
  {
    id: 'course-001',
    title: 'Complete Web Development Bootcamp',
    description:
      'Learn HTML, CSS, JavaScript, React, Node.js and become a full-stack developer',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/web%20development-eGhUrG8CgTADGuiRwbYVzwBQMfe9qH.jpg',
    instructor: INSTRUCTORS[0],
    price: 29999,
    duration: 90,
    level: 'beginner',
    rating: 4.8,
    reviews: 2450,
    studentsEnrolled: 15300,
    curriculum: [
      {
        id: 'mod-1',
        title: 'HTML Fundamentals',
        topics: ['Tags', 'Semantic HTML', 'Forms'],
      },
      {
        id: 'mod-2',
        title: 'CSS & Styling',
        topics: ['Selectors', 'Flexbox', 'Grid'],
      },
      {
        id: 'mod-3',
        title: 'JavaScript Basics',
        topics: ['Variables', 'Functions', 'DOM'],
      },
    ],
    materials: [
      {
        id: 'mat-1',
        title: 'HTML Guide',
        type: 'pdf',
      },
      {
        id: 'mat-2',
        title: 'CSS Tutorial',
        type: 'video',
      },
    ],
    createdAt: '2024-01-15',
  },
  {
    id: 'course-002',
    title: 'Data Science with Python',
    description:
      'Master data analysis, visualization, and machine learning using Python',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/python.jfif-3lez3237HYn5hFLVbCOun5LwszMXHm.jpeg',
    instructor: INSTRUCTORS[1],
    price: 34999,
    duration: 120,
    level: 'intermediate',
    rating: 4.9,
    reviews: 1890,
    studentsEnrolled: 8900,
    curriculum: [
      {
        id: 'mod-4',
        title: 'Python Basics',
        topics: ['Variables', 'Data Types', 'Control Flow'],
      },
      {
        id: 'mod-5',
        title: 'Data Analysis with Pandas',
        topics: ['DataFrames', 'Cleaning', 'Aggregation'],
      },
    ],
    materials: [],
    createdAt: '2024-01-20',
  },
  {
    id: 'course-003',
    title: 'iOS App Development',
    description: 'Build professional iOS apps using Swift and SwiftUI',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tc_iphone_banner-WpaOzUTSSAhJiWPXEy2Uu2aLtQTSnR.jpg',
    instructor: INSTRUCTORS[2],
    price: 39999,
    duration: 100,
    level: 'intermediate',
    rating: 4.7,
    reviews: 1250,
    studentsEnrolled: 5600,
    curriculum: [],
    materials: [],
    createdAt: '2024-02-01',
  },
  {
    id: 'course-004',
    title: 'Cloud Architecture on AWS',
    description: 'Design and deploy scalable applications on Amazon Web Services',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=500',
    instructor: INSTRUCTORS[3],
    price: 44999,
    duration: 80,
    level: 'advanced',
    rating: 4.6,
    reviews: 980,
    studentsEnrolled: 4200,
    curriculum: [],
    materials: [],
    createdAt: '2024-02-10',
  },
  {
    id: 'course-005',
    title: 'React Advanced Patterns',
    description: 'Master advanced React concepts and build scalable applications',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Adv-React-a6h0TYIPb8Fc7D6s8IbsMXXfkCf1cn.png',
    instructor: INSTRUCTORS[0],
    price: 24999,
    duration: 60,
    level: 'advanced',
    rating: 4.8,
    reviews: 1620,
    studentsEnrolled: 7800,
    curriculum: [],
    materials: [],
    createdAt: '2024-02-15',
  },
  {
    id: 'course-006',
    title: 'UI/UX Design Masterclass',
    description: 'Learn design thinking, Figma, and user research',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/courses-7-sZTVNHFQcuH2EZavT9AHbE8ir6yJhS.jpg',
    instructor: INSTRUCTORS[2],
    price: 19999,
    duration: 75,
    level: 'beginner',
    rating: 4.9,
    reviews: 2100,
    studentsEnrolled: 12400,
    curriculum: [],
    materials: [],
    createdAt: '2024-02-20',
  },
  {
    id: 'course-007',
    title: 'Machine Learning Fundamentals',
    description: 'Understand ML algorithms, neural networks, and TensorFlow',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/machine%20learning-9BMy5s1Zr0jPoCTlYJRI9rgCUIXI0Q.jpg',
    instructor: INSTRUCTORS[1],
    price: 49999,
    duration: 130,
    level: 'advanced',
    rating: 4.7,
    reviews: 890,
    studentsEnrolled: 3400,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-01',
  },
  {
    id: 'course-008',
    title: 'TypeScript for Professionals',
    description: 'Master TypeScript and build type-safe applications',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/typescripting.jfif-6VojxG7QtRxJ5dvOIoVAQiuhenfPzA.jpeg',
    instructor: INSTRUCTORS[0],
    price: 18999,
    duration: 55,
    level: 'intermediate',
    rating: 4.8,
    reviews: 1450,
    studentsEnrolled: 6700,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-05',
  },
  {
    id: 'course-009',
    title: 'Blockchain Development',
    description: 'Build decentralized applications with Solidity and Web3',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/blockchain-eG8Mge3qyA2y20nQ4A1dOh7pIJtwNQ.jpg',
    instructor: INSTRUCTORS[3],
    price: 54999,
    duration: 100,
    level: 'advanced',
    rating: 4.6,
    reviews: 620,
    studentsEnrolled: 2800,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-10',
  },
  {
    id: 'course-010',
    title: 'Graphic Design Essentials',
    description: 'Learn design principles, color theory, and Adobe Creative Suite',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/graphic-design-essentials-CUt9vatoo4fuH7AI5NKaODGS4iy1pi.png',
    instructor: INSTRUCTORS[2],
    price: 16999,
    duration: 65,
    level: 'beginner',
    rating: 4.9,
    reviews: 2800,
    studentsEnrolled: 14200,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-15',
  },
  {
    id: 'course-011',
    title: 'Cybersecurity Fundamentals',
    description: 'Learn network security, encryption, and ethical hacking principles',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/blog-26-EEjwcWN7JYU7PjNHoz4gXezRlj2Rnd.jpg',
    instructor: INSTRUCTORS[3],
    price: 39999,
    duration: 85,
    level: 'intermediate',
    rating: 4.8,
    reviews: 1120,
    studentsEnrolled: 5400,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-20',
  },
  {
    id: 'course-012',
    title: 'Artificial Intelligence Essentials',
    description: 'Introduction to AI, machine learning models, and real-world applications',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/blog-26-EEjwcWN7JYU7PjNHoz4gXezRlj2Rnd.jpg',
    instructor: INSTRUCTORS[1],
    price: 44999,
    duration: 95,
    level: 'intermediate',
    rating: 4.9,
    reviews: 1350,
    studentsEnrolled: 6800,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-25',
  },
  {
    id: 'course-013',
    title: 'Computer Basics & IT Fundamentals',
    description: 'Master computer hardware, operating systems, and IT support essentials',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    instructor: INSTRUCTORS[0],
    price: 14999,
    duration: 50,
    level: 'beginner',
    rating: 4.7,
    reviews: 2100,
    studentsEnrolled: 18900,
    curriculum: [],
    materials: [],
    createdAt: '2024-03-30',
  },
];

// Products
export const PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'MacBook Pro 16"',
    category: 'laptops',
    price: 2499999,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    description: 'Professional laptop for developers',
    specs: { processor: 'M3 Max', ram: '36GB', storage: '1TB SSD' },
    rating: 4.9,
    reviews: 450,
    stock: 25,
    inStock: true,
    brand: 'Apple',
    createdAt: '2024-01-01',
  },
  {
    id: 'prod-002',
    name: 'Dell XPS 15',
    category: 'laptops',
    price: 1999999,
    image: 'https://images.unsplash.com/photo-1588872657840-e59fbf172d60?w=500',
    description: 'Powerful Windows laptop for developers',
    specs: { processor: 'Intel i9', ram: '32GB', storage: '1TB SSD' },
    rating: 4.7,
    reviews: 380,
    stock: 30,
    inStock: true,
    brand: 'Dell',
    createdAt: '2024-01-02',
  },
  {
    id: 'prod-003',
    name: 'Lenovo ThinkPad X1',
    category: 'laptops',
    price: 1499999,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    description: 'Business laptop with excellent keyboard',
    specs: { processor: 'Intel i7', ram: '16GB', storage: '512GB SSD' },
    rating: 4.8,
    reviews: 320,
    stock: 40,
    inStock: true,
    brand: 'Lenovo',
    createdAt: '2024-01-03',
  },
  {
    id: 'prod-004',
    name: 'iPhone 15 Pro Max',
    category: 'phones',
    price: 1799999,
    image: 'https://images.unsplash.com/photo-1592286927505-1d6a3fc7e3a7?w=500',
    description: 'Latest flagship iOS device',
    specs: { storage: '256GB', color: 'Titanium Black', camera: '48MP' },
    rating: 4.8,
    reviews: 1200,
    stock: 50,
    inStock: true,
    brand: 'Apple',
    createdAt: '2024-01-04',
  },
  {
    id: 'prod-005',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'phones',
    price: 1699999,
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf7ce2813?w=500',
    description: 'Powerful Android flagship phone',
    specs: { storage: '256GB', display: '6.8" Dynamic AMOLED', camera: '200MP' },
    rating: 4.7,
    reviews: 980,
    stock: 45,
    inStock: true,
    brand: 'Samsung',
    createdAt: '2024-01-05',
  },
  {
    id: 'prod-006',
    name: 'Google Pixel 8 Pro',
    category: 'phones',
    price: 1299999,
    image: 'https://images.unsplash.com/photo-1514993713792-34a662b1d7f1?w=500',
    description: 'Pure Android experience with AI features',
    specs: { storage: '128GB', display: '6.7" OLED', camera: '50MP' },
    rating: 4.8,
    reviews: 650,
    stock: 35,
    inStock: true,
    brand: 'Google',
    createdAt: '2024-01-06',
  },
  {
    id: 'prod-007',
    name: 'Sony WH-1000XM5',
    category: 'accessories',
    price: 399999,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    description: 'Premium noise-cancelling headphones',
    specs: { batteryLife: '40 hours', noiseCancel: 'Active', weight: '250g' },
    rating: 4.9,
    reviews: 2200,
    stock: 100,
    inStock: true,
    brand: 'Sony',
    createdAt: '2024-01-07',
  },
  {
    id: 'prod-008',
    name: 'Apple AirPods Pro',
    category: 'accessories',
    price: 249999,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    description: 'Wireless earbuds with active noise cancellation',
    specs: { batteryLife: '6 hours', noiseCancel: 'Active', weight: '5g' },
    rating: 4.8,
    reviews: 3100,
    stock: 120,
    inStock: true,
    brand: 'Apple',
    createdAt: '2024-01-08',
  },
  {
    id: 'prod-009',
    name: 'Logitech MX Master 3S',
    category: 'accessories',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=500',
    description: 'Advanced wireless mouse for professionals',
    specs: { batteryLife: '70 days', dpi: '8000', weight: '141g' },
    rating: 4.7,
    reviews: 1800,
    stock: 150,
    inStock: true,
    brand: 'Logitech',
    createdAt: '2024-01-09',
  },
  {
    id: 'prod-010',
    name: 'Keychron K8 Pro',
    category: 'accessories',
    price: 199999,
    image: 'https://images.unsplash.com/photo-1587829191301-26d93b60c993?w=500',
    description: 'Mechanical keyboard for developers',
    specs: { switches: 'Gateron Hot Swap', layout: '87 keys', wireless: true },
    rating: 4.8,
    reviews: 950,
    stock: 80,
    inStock: true,
    brand: 'Keychron',
    createdAt: '2024-01-10',
  },
];

// Sample Students
export const SAMPLE_STUDENTS: Student[] = [
  {
    id: 'student-001',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '08012345678',
    role: 'student',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    studentId: 'IFY-STU-00001',
    enrolledCourses: ['course-001', 'course-005'],
    totalSpent: 54998,
    createdAt: '2024-01-10',
  },
  {
    id: 'student-002',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '08087654321',
    role: 'student',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    studentId: 'IFY-STU-00002',
    enrolledCourses: ['course-002', 'course-007'],
    totalSpent: 84998,
    createdAt: '2024-01-12',
  },
];

// Sample Enrollments
export const SAMPLE_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enroll-001',
    studentId: 'student-001',
    courseId: 'course-001',
    startDate: '2024-04-01',
    endDate: '2024-06-29',
    progressPercentage: 65,
    completedDays: 59,
    totalClassDays: 90,
    attendancePercentage: 92,
    status: 'in_progress',
    dailyProgress: Array(90)
      .fill(false)
      .map((_, i) => i < 59),
    certificateId: undefined,
  },
  {
    id: 'enroll-002',
    studentId: 'student-001',
    courseId: 'course-005',
    startDate: '2024-05-15',
    endDate: '2024-07-14',
    progressPercentage: 40,
    completedDays: 24,
    totalClassDays: 60,
    attendancePercentage: 88,
    status: 'in_progress',
    dailyProgress: Array(60)
      .fill(false)
      .map((_, i) => i < 24),
    certificateId: undefined,
  },
];

// Sample Certificates
export const SAMPLE_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-001',
    studentId: 'student-002',
    courseId: 'course-010',
    certificateNumber: 'IFYCERT-2024-001',
    issuedAt: '2024-03-15',
    courseName: 'Graphic Design Essentials',
    studentName: 'Jane Smith',
    instructorName: 'Emily Rodriguez',
    courseDuration: 65,
  },
];

// Sample Payments
export const SAMPLE_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    transactionId: 'TXN-2024-001',
    studentId: 'student-001',
    amount: 29999,
    currency: 'NGN',
    type: 'course',
    status: 'completed',
    paymentMethod: 'Card',
    createdAt: '2024-04-01',
    description: 'Complete Web Development Bootcamp',
  },
  {
    id: 'pay-002',
    transactionId: 'TXN-2024-002',
    studentId: 'student-001',
    amount: 24999,
    currency: 'NGN',
    type: 'course',
    status: 'completed',
    paymentMethod: 'Card',
    createdAt: '2024-05-15',
    description: 'React Advanced',
  },
  {
    id: 'pay-003',
    transactionId: 'TXN-2024-003',
    studentId: 'student-002',
    amount: 34999,
    currency: 'NGN',
    type: 'course',
    status: 'completed',
    paymentMethod: 'Transfer',
    createdAt: '2024-02-20',
    description: 'Data Science with Python',
  },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 'test-001',
    studentId: 'student-001',
    studentName: 'Chukwu Okonkwo',
    studentImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    courseId: 'course-001',
    courseName: 'Complete Web Development Bootcamp',
    rating: 5,
    text: 'This bootcamp completely transformed my career! The instructors are incredibly knowledgeable and the curriculum is industry-relevant. I landed a job as a junior developer within 3 months of completing the course.',
    createdAt: '2024-05-10',
    status: 'approved' as const,
  },
  {
    id: 'test-002',
    studentId: 'student-002',
    studentName: 'Amara Okafor',
    studentImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    courseId: 'course-002',
    courseName: 'Data Science with Python',
    rating: 5,
    text: 'The Data Science course exceeded my expectations. The practical projects were real-world scenarios and helped me build a strong portfolio. Highly recommended!',
    createdAt: '2024-05-12',
    status: 'approved' as const,
  },
  {
    id: 'test-003',
    studentId: 'student-003',
    studentName: 'Emeka Eze',
    studentImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    courseId: 'course-003',
    courseName: 'iOS App Development',
    rating: 4.5,
    text: 'Great course structure and amazing instructor support. Swift concepts were explained clearly with hands-on projects. Would definitely recommend to anyone wanting to learn iOS development.',
    createdAt: '2024-05-14',
    status: 'approved' as const,
  },
  {
    id: 'test-004',
    studentId: 'student-004',
    studentName: 'Zainab Ibrahim',
    studentImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    courseId: 'course-004',
    courseName: 'Cloud Architecture on AWS',
    rating: 5,
    text: 'The AWS course is comprehensive and well-structured. I got certified and now I can design scalable cloud solutions. Best investment in my tech career!',
    createdAt: '2024-05-15',
    status: 'approved' as const,
  },
];

// Partners
export const PARTNERS = [
  {
    id: 'partner-001',
    name: 'Microsoft',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/512px-Microsoft_logo.svg.png',
    description: 'Global technology leader and enterprise solutions provider',
    website: 'https://www.microsoft.com',
    category: 'Technology',
    status: 'active' as const,
  },
  {
    id: 'partner-002',
    name: 'Google',
    logo: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
    description: 'Leading search and cloud infrastructure company',
    website: 'https://www.google.com',
    category: 'Technology',
    status: 'active' as const,
  },
  {
    id: 'partner-003',
    name: 'Amazon AWS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1024px-Amazon_Web_Services_Logo.svg.png',
    description: 'Cloud computing and infrastructure services',
    website: 'https://aws.amazon.com',
    category: 'Cloud',
    status: 'active' as const,
  },
  {
    id: 'partner-004',
    name: 'Meta',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Facebook_Logo_%282019%29.png',
    description: 'Social platform and developer tools provider',
    website: 'https://www.meta.com',
    category: 'Technology',
    status: 'active' as const,
  },
  {
    id: 'partner-005',
    name: 'GitHub',
    logo: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
    description: 'Developer collaboration and version control platform',
    website: 'https://www.github.com',
    category: 'Development',
    status: 'active' as const,
  },
  {
    id: 'partner-006',
    name: 'Vercel',
    logo: 'https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_dark_background.png',
    description: 'Frontend deployment and edge infrastructure',
    website: 'https://vercel.com',
    category: 'Cloud',
    status: 'active' as const,
  },
];

export const DEFAULT_STUDENT: Student = SAMPLE_STUDENTS[0];
export const DEFAULT_ADMIN: User = {
  id: 'admin-001',
  name: 'Admin User',
  email: 'admin@ifybugsy.com',
  phone: '08000000000',
  role: 'admin',
  profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
  createdAt: '2024-01-01',
};
